cookie:
  expiry_days: 1
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    op3522728e:
      email: maingateparlour
      failed_login_attempts: 0
      forgot_password: true
      isactive: true
      logged_in: null
      name: evening
      password: '654321'
    op3522728m:
      email: maingateparlour
      failed_login_attempts: 0
      forgot_password: true
      isactive: true
      logged_in: null
      name: morning
      password: '123456'
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0
      forgot_password: false
      isactive: true
      logged_in: false
      name: Admin
      password: $2b$12$ySgIxyZNb4fwhxlvaazjtunfJGLN7wFsrd1NXipTGf3wSLONbdCUC
    admin2:
      email: admin@gmail.com
      failed_login_attempts: 0
      forgot_password: true
      isactive: true
      logged_in: null
      name: sarvagna
      password: $2b$12$ySgIxyZNb4fwhxlvaazjtunfJGLN7wFsrd1NXipTGf3wSLONbdCUC
    op2:
      email: test
      failed_login_attempts: 0
      forgot_password: null
      isactive: null
      logged_in: null
      name: test4
      password: $2b$12$ySgIxyZNb4fwhxlvaazjtunfJGLN7wFsrd1NXipTGf3wSLONbdCUC
    operator:
      email: op@mail.com
      failed_login_attempts: 0
      forgot_password: null
      isactive: true
      logged_in: null
      name: Test2
      password: $2b$12$JmqhD8ykMoJXpnGpcMo0VuSP/ZGyEipo6kJg9Iz8nnrL0Ilwr4FSW
    pos:
      email: pos@gmail.com
      failed_login_attempts: 0
      forgot_password: true
      isactive: true
      logged_in: null
      name: sarvagna
      password: $2b$12$ySgIxyZNb4fwhxlvaazjtunfJGLN7wFsrd1NXipTGf3wSLONbdCUC
    post:
      email: post@test.com
      failed_login_attempts: 0
      forgot_password: null
      isactive: null
      logged_in: null
      name: test4
      password: $2b$12$xRfOk0t..fqQsXB2WCs9gewFpJ44541QMjD64gbeng/yn.2FXmYOS
    timekeeper:
      email: secondtimekeeper@mail.com
      failed_login_attempts: 0
      forgot_password: true
      isactive: true
      logged_in: null
      name: Test
      password: $2b$12$24gkmB2.ZzUTfr7tmmm9WOnDIHAuEpOIkIfSptNIqceYymd.7Y4xy
    timekeeper2:
      email: test@mil.com
      failed_login_attempts: 0
      forgot_password: null
      isactive: true
      logged_in: null
      name: Test3
      password: $2b$12$8MswqgomRidB18L4VKJPLO1J4aK43pnVDfMm0f5qdDKHv52pi24z6
preauthorized:
  emails:
  - super_admin@gmail.com
